apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: busybox-node-selector
  name: busybox-node-selector-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox-node-selector
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: busybox-node-selector
    spec:
      containers:
      - image: busybox
        imagePullPolicy: Always
        command: ["/bin/sh","-c","sleep 1000"]
        name: busybox-1
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
      nodeSelector:
        app: projectA


