apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  sessionAffinity: None
  type: LoadBalancer
# underlying provider will create load balancer and populate below values with lb name like mentioned below
#status:
#  loadBalancer:
#    ingress:
#    - hostname: a136742fd520311e9a1dd0aa90c6de73-1424809639.us-east-1.elb.amazon
