apiVersion: v1
kind: PersistentVolume
metadata:
 name: pv-aws
spec:
 capacity:
   storage: 12Gi
 accessModes:
   - ReadWriteOnce
 persistentVolumeReclaimPolicy: Recycle
 storageClassName: slow
 awsElasticBlockStore: 
    fsType: "ext4" 
    volumeID: "vol-xxx" 
