apiVersion: v1
kind: PersistentVolume
metadata:
 name: pv-aws
spec:
 capacity:
   storage: 1Gi
 accessModes:
   - ReadWriteOnce
 persistentVolumeReclaimPolicy: Delete
 storageClassName: default
 awsElasticBlockStore: 
    fsType: "ext4" 
    volumeID: "vol-xxx" 
